[package]
name = "chunk-surfer"
version = "0.1.2-beta.3"
description = "Chunk Surfer desktop shell"
authors = ["cbassuarez"]
edition = "2021"

[lib]
name = "chunk_surfer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8.7"
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-log = "2"
tauri-plugin-opener = "2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Threading"] }
