[package]
name = "chunk-surfer"
version = "0.1.1-beta.2"
description = "Chunk Surfer desktop shell"
authors = ["cbassuarez"]
edition = "2021"

[lib]
name = "chunk_surfer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
rand = "0.8.7"
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-log = "2"
tauri-plugin-opener = "2"
