// Pressable things are plastic, and the art has a licence.
//
// Two contracts that are easy to break silently: an icon set that gets swapped
// for hand-drawn approximations again, and a prompt line that quietly goes back
// to printing `[R]` as text.

import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { ICON_PATHS, ICON_STROKE, ICON_VIEWBOX } from '../src/render/generated/icon-paths.js';
import { VERB_ICON_CELLS, hasVerbIcon } from '../src/render/verb-icons.js';
import { THEMES, setActiveSurface, uiRoleColor } from '../src/render/palette.js';

test('the verb icons are real vendored art, not hand-rolled shapes', () => {
  for (const id of ['light', 'recorder', 'bag', 'playback']) {
    const icon = ICON_PATHS[id];
    assert.ok(icon, `${id} is vendored`);
    assert.ok(icon.source, `${id} records which glyph it came from`);
    assert.ok(icon.paths.length, `${id} has geometry`);
    for (const d of icon.paths) assert.match(d, /^[Mm]/, `${id} path is real path data`);
    assert.ok(hasVerbIcon(id), `${id} is reachable from the renderer`);
  }
  assert.equal(ICON_VIEWBOX, 24);
  assert.equal(ICON_STROKE, 2);
});

test('the icon licence travels with the art', () => {
  assert.ok(existsSync('assets/licenses/lucide-ISC.txt'), 'the ISC text is vendored');
  const licence = readFileSync('assets/licenses/lucide-ISC.txt', 'utf8');
  assert.match(licence, /ISC License/, 'it is the licence it claims to be');
  const generated = readFileSync('src/render/generated/icon-paths.js', 'utf8');
  assert.match(generated, /Lucide/, 'the generated file names its source');
  assert.match(generated, /ISC/, 'and its licence');
  assert.match(generated, /GENERATED by/, 'and says it is generated');
});

test('a bracketed key prompt is drawn as a keycap, at the same width', () => {
  const source = readFileSync('src/render/prompt-glyphs.js', 'utf8');
  assert.match(source, /drawKeycap\(/, 'the prompt line draws real keycaps');
  // The cap must occupy exactly the cells the bracket run measured, or every
  // right-aligned rail in the game shifts.
  assert.match(source, /drawKeycap\(cx, y[^,]*, glyph\.cells,/,
    'the cap is exactly as wide as the text it replaces');
  assert.match(source, /VERB_ICON_CELLS/, 'and an icon still costs its own cells');
  assert.equal(VERB_ICON_CELLS, 2);
});

test('pressable surfaces share one plastic vocabulary', () => {
  const keycap = readFileSync('src/render/keycap.js', 'utf8');
  assert.match(keycap, /export function drawKeycap/);
  assert.match(keycap, /export function drawCapLegend/);
  // keycap.js is the floor under both, so it must not reach back up into
  // presentation.js — that is the cycle this split exists to avoid.
  assert.doesNotMatch(keycap, /from '\.\/presentation\.js'/,
    'the shared floor never imports the surface above it');
  const presentation = readFileSync('src/render/presentation.js', 'utf8');
  assert.match(presentation, /export function drawLampButton/, 'legend caps live on the panel surface');
  assert.match(presentation, /drawCapLegend/, 'and print their legends with the shared ink');
});

test('ink is a palette role, dark, and never glows', () => {
  // Every theme has to carry the token: themeRoleColor falls back to PHOSPHOR
  // for an unknown role, so a theme without capInk prints a legend in the same
  // colour as the lit cap it is supposed to be readable on.
  for (const [name, theme] of Object.entries(THEMES)) {
    assert.ok(theme.capInk, `${name} defines capInk`);
  }
  for (const surface of ['amber', 'green']) {
    setActiveSurface(surface);
    const ink = uiRoleColor('ui-ink');
    const lit = uiRoleColor('ui-primary');
    assert.notEqual(ink, lit, `${surface}: ink is not the phosphor`);
    // Dark enough to read as print on a lit cap.
    const [, r, g, b] = /^#(..)(..)(..)$/.exec(ink).map((v, i) => (i ? parseInt(v, 16) : v));
    assert.ok(r + g + b < 150, `${surface}: ink is dark (${ink})`);
  }
});

test('the atlas colours ink from the palette, not from the CSS default', () => {
  const atlas = readFileSync('src/render/atlas.js', 'utf8');
  // The bug this pins: `isVfd ? uiRoleColor(...) : resolveStyle(...)` sent
  // 'ui-ink' down the CSS branch, which has no entry for it and defaults to
  // amber — a legend printed the same colour as the cap under it.
  assert.match(atlas, /isVfd \|\| isInk \? uiRoleColor/,
    'ink takes its colour from the palette like every other ui- role');
  assert.match(atlas, /const isInk = cls === 'ui-ink'/, 'ink is recognised');
  assert.match(atlas, /const isVfd = cls\.startsWith\('ui-'\) && !isInk/,
    'and is excluded from the phosphor halation');
});

test('both icon renderers accept an ink override', () => {
  for (const file of ['src/render/bag-icons.js', 'src/render/combat-view.js']) {
    const source = readFileSync(file, 'utf8');
    assert.match(source, /ink = null/, `${file} takes an ink override`);
    assert.match(source, /ink \|\|/, `${file} lets ink win over the tone`);
  }
  // A symbol printed on plastic neither flickers nor blooms.
  const bag = readFileSync('src/render/bag-icons.js', 'utf8');
  assert.match(bag, /ink \? 1 : uiFlickerAlpha/, 'ink does not flicker');
  assert.match(bag, /active: ink \? false : active/, 'ink does not bloom');
});
