import { spawnSync } from 'node:child_process';
import process from 'node:process';

const tests = [
  'test/bag.spec.mjs',
  'test/dock-setup.spec.mjs',
  'test/loading-dock-haunting.spec.mjs',
  'test/loading-dock-investigation.spec.mjs',
  'test/loading-dock-model-shortlist.spec.mjs',
  'test/battle-voices.spec.mjs',
  'test/endings-audit.spec.mjs',
  'test/combat-loadout.spec.mjs',
  'test/bag-skills.spec.mjs',
  'test/loadout-briefing.spec.mjs',
  'test/combat-presentation.spec.mjs',
  'test/combat-tutorial.spec.mjs',
  'test/battle-narrative.spec.mjs',
  'test/prompt-token-budget.test.mjs',
  'test/eula-gate.test.mjs',
  'test/vfd-select.test.mjs',
  'test/pad-glyphs.test.mjs',
  'test/studio-layout.test.mjs',
  'test/lighting-rig.spec.mjs',
  'test/conservatory-power.spec.mjs',
  'test/electrical-hum.spec.mjs',
  'test/torch-lighting.spec.mjs',
  'test/glass-pass.test.mjs',
  'test/visual-polish-contract.test.mjs',
  'test/map-core.spec.mjs',
  'test/map-live-data.spec.mjs',
  'test/minimap-telemetry.test.mjs',
  'test/hush-telemetry.spec.mjs',
  'test/acoustic-core.spec.mjs',
  'test/recordist-acoustics.spec.mjs',
  'test/hush-audio-pure.spec.mjs',
  'test/hush-contact.spec.mjs',
  'test/presence-pursuit.spec.mjs',
  'test/presence-contact.spec.mjs',
  'test/hush-audio-runtime.spec.mjs',
  'test/hush-mix.spec.mjs',
  'test/hush-audio-firewall.spec.mjs',
  'test/audio-context-recovery.test.mjs',
  'test/background-audio.test.mjs',
  'test/fear-pressure.spec.mjs',
  'test/fear-overlay.test.mjs',
  'test/controller.test.mjs',
  'test/controller-ui.test.mjs',
  'test/controller-diagram-layout.test.mjs',
  'test/controller-callouts.test.mjs',
  'test/prompt-glyphs.test.mjs',
  'test/input-prompts.test.mjs',
  'test/mic-input.test.mjs',
  'test/settings-about-tab.test.mjs',
  'test/god-menu.test.mjs',
  'test/pause-menu.test.mjs',
  'test/sample-field-boot-contract.test.mjs',
  'test/map-bag-integration.spec.mjs',
  'test/map-information-firewall.spec.mjs',
  'test/progression-pure.spec.mjs',
  'test/progression-profile.spec.mjs',
  'test/progression-runtime.spec.mjs',
  'test/progression-migration.spec.mjs',
  'test/stair-anomaly.spec.mjs',
  'test/academic-gallery.spec.mjs',
  'test/platform-sync.spec.mjs',
  'test/storage-platform.spec.mjs',
  'test/launch-parity.spec.mjs',
  'test/dev-launch-contract.test.mjs',
  'test/release-workflow.spec.mjs',
  'test/windows-portable.test.mjs',
  'test/itch-release.test.mjs',
  'test/conversation-choice-state.test.mjs',
  'test/menu-layout-contract.spec.mjs',
  'test/transcript-layout.test.mjs',
  'test/title-cinematic.test.mjs',
  'test/opening-credits.test.mjs',
  'test/credits.test.mjs',
  'test/visual-smoke-captures.test.mjs',
  'test/renderer-policy.test.mjs',
  'test/acquisition-props.test.mjs',
  'test/look-profiles.test.mjs',
  'test/diffusion-lens-contract.test.mjs',
  'test/material-mutation.test.mjs',
  'test/jumpscare-art.spec.mjs',
  'test/material-cache-contract.test.mjs',
  'test/tuning-fork-asset.test.mjs',
  'test/door-system.spec.mjs',
  'test/conservatory-space-layout.test.mjs',
  'test/natatorium-water.test.mjs',
  'test/radio-progression.spec.mjs',
  'test/battle-music.spec.mjs',
  'test/combat-state.spec.mjs',
  'test/redaction-system.spec.mjs',
  'test/personalized-interference.spec.mjs',
  'test/chunk-surf-state.spec.mjs',
  'test/chunk-surf-visual.spec.mjs',
  'test/source-space-chapter.spec.mjs',
  'test/chapel-tower-state.spec.mjs',
  'test/bell-tower.spec.mjs',
  'test/tower-on-foot-route.spec.mjs',
  'test/bell-stem-assets.test.mjs',
  'test/source-tower-transition.spec.mjs',
  'test/narrative-studio.spec.mjs',
];

for (const file of tests) {
  const result = spawnSync(process.execPath, [file], {
    cwd: process.cwd(),
    stdio: 'inherit',
  });
  if (result.status !== 0) process.exit(result.status || 1);
}

console.log(`all ${tests.length} test files passed`);
