import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { FIREBALL_SURFACE_LABELS,substantiallyOnscreenPosition } from '../src/platform/personalized-window-effects.js';

assert.deepEqual(FIREBALL_SURFACE_LABELS,['fireball-cast-1','fireball-cast-2','fireball-cast-3','fireball-cast-4']);
assert.deepEqual(substantiallyOnscreenPosition({position:{x:-3900,y:-200},size:{width:200,height:200},monitor:{position:{x:-3840,y:-120},size:{width:3840,height:2160}}}),{x:-3880,y:-160});
const rust=readFileSync(new URL('../src-tauri/src/window_choreography.rs',import.meta.url),'utf8');
const capability=readFileSync(new URL('../src-tauri/capabilities/personalized-interference.json',import.meta.url),'utf8');
assert.doesNotMatch(rust,/set_fullscreen|chunk_window_choreography_execute|window-choreography-recovery/);
assert.doesNotMatch(capability,/allow-set-(?:position|size|fullscreen|title)/);
assert.match(capability,/allow-set-focus/);
assert.match(rust,/set_ignore_cursor_events\(false\)/);assert.match(rust,/set_ignore_cursor_events\(true\)/);assert.match(rust,/count>0&&count<=4/);
assert.match(rust,/chunk_fireball_cast_focus_main/);
const effects=readFileSync(new URL('../src/platform/personalized-window-effects.js',import.meta.url),'utf8');
assert.match(effects,/focusable:true/);assert.match(effects,/skipTaskbar:true/);
assert.match(effects,/let surface=await api\.WebviewWindow\.getByLabel\(label\)/);
assert.match(effects,/surface=new api\.WebviewWindow\(label/);
const cast=readFileSync(new URL('../src/fireball-cast.js',import.meta.url),'utf8');
assert.match(cast,/pointerdown[\s\S]{0,220}strike\(\)/);
assert.match(cast,/emit\('fireball-cast-hit',payload\)/);
console.log('fireball native surface contracts passed');
