// VENDOR THE ICONS WE ACTUALLY USE.
//
// The verb rail was drawing hand-rolled vector approximations of a torch, a reel
// and a case. They were fine as placeholders and wrong as artwork: nobody drew
// them, they do not agree with each other about weight or corner radius, and
// there is no license behind them because there is no source.
//
// Lucide (ISC) is a real set with a real license and a consistent 24x24, 2px,
// round-cap grammar. Only the handful of glyphs this game uses are extracted, as
// plain path data, into src/render/generated/icon-paths.js — so the runtime has
// no dependency on the package and the licence travels with the art.
//
//   npm install --no-save lucide-static
//   node tools/chunk_surfer/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'node_modules/lucide-static/icons';
const WANT = {
  light: 'flashlight',
  recorder: 'disc-3',
  bag: 'briefcase',
  playback: 'play',
};

// <rect> is the one primitive Lucide uses that is not already a path.
function rectToPath(attrs) {
  const n = (k) => Number(attrs[k] || 0);
  const x = n('x'), y = n('y'), w = n('width'), h = n('height');
  const r = Math.min(n('rx') || 0, w / 2, h / 2);
  if (!r) return `M${x} ${y}H${x + w}V${y + h}H${x}Z`;
  return `M${x + r} ${y}H${x + w - r}A${r} ${r} 0 0 1 ${x + w} ${y + r}`
    + `V${y + h - r}A${r} ${r} 0 0 1 ${x + w - r} ${y + h}`
    + `H${x + r}A${r} ${r} 0 0 1 ${x} ${y + h - r}`
    + `V${y + r}A${r} ${r} 0 0 1 ${x + r} ${y}Z`;
}

function attrsOf(tag) {
  const out = {};
  for (const m of tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) out[m[1]] = m[2];
  return out;
}

const icons = {};
for (const [id, file] of Object.entries(WANT)) {
  const svg = readFileSync(`${SRC}/${file}.svg`, 'utf8');
  const parts = [];
  for (const m of svg.matchAll(/<path\b([^>]*)\/>/g)) {
    const a = attrsOf(m[1]);
    if (a.d) parts.push({ d: a.d });
  }
  for (const m of svg.matchAll(/<rect\b([^>]*)\/>/g)) parts.push({ d: rectToPath(attrsOf(m[1])) });
  for (const m of svg.matchAll(/<circle\b([^>]*)\/>/g)) {
    const a = attrsOf(m[1]);
    const cx = Number(a.cx), cy = Number(a.cy), r = Number(a.r);
    parts.push({ d: `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${r * 2} 0a${r} ${r} 0 1 0 ${-r * 2} 0Z` });
  }
  if (!parts.length) throw new Error(`no geometry extracted for ${file}`);
  icons[id] = { source: file, paths: parts.map((p) => p.d) };
}

const header = `// GENERATED by tools/chunk_surfer/build-icons.mjs — do not edit.
//
// Icon geometry from Lucide (https://lucide.dev), ISC License.
// Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as part
// of Feather (MIT). All other copyright (c) for Lucide are held by Lucide
// Contributors 2022. See assets/licenses/lucide-ISC.txt for the full text.
//
// Every glyph is stroked on a 24x24 box with a 2px round-capped, round-joined
// pen — draw them that way and they sit correctly beside each other.

export const ICON_VIEWBOX = 24;
export const ICON_STROKE = 2;

export const ICON_PATHS = Object.freeze(`;

writeFileSync('src/render/generated/icon-paths.js',
  `${header}${JSON.stringify(icons, null, 2)});\n`);
console.log(`wrote ${Object.keys(icons).length} icons:`, Object.keys(icons).join(', '));
